"""Trace the Chat360 brand mark into a crisp SVG.

Source: studio/public/brand/chat360-ai-logo.png — the CHAT360 .AI wordmark Kevin
supplied (400x187, flat colours on transparency). Each pixel is unmixed into its
three inks (mint, gray, white); each ink is upscaled from its anti-aliased
coverage, thresholded and traced with potrace, so the vector follows the real
logo instead of a redraw.

Writes studio/public/brand/chat360-ai-logo.svg and src/library/logoPaths.ts.
Run: python3 scripts/trace-logo.py   (needs: pip install pillow numpy potracer)
"""
import json
import pathlib

import numpy as np
import potrace
from PIL import Image, ImageFilter

STUDIO = pathlib.Path(__file__).resolve().parents[1]
SRC = STUDIO / "public" / "brand" / "chat360-ai-logo.png"
OUT_SVG = STUDIO / "public" / "brand" / "chat360-ai-logo.svg"
OUT_TS = STUDIO / "src" / "library" / "logoPaths.ts"
SCALE = 10

INKS = {
    "mint": (0x2A, 0xD3, 0xA3),
    "gray": (0x57, 0x57, 0x56),
    "white": (0xFF, 0xFF, 0xFF),
}

rgba = np.asarray(Image.open(SRC).convert("RGBA")).astype(np.float64) / 255.0
alpha = rgba[..., 3]
premult = rgba[..., :3] * alpha[..., None]
# Unmix per region with the two inks that can occur there: the white ".AI" only
# lives inside the bubble (x >= BUBBLE_X), the gray "360" only left of it.
# (A 3-ink solve reads light-gray edge pixels as gray+white and bites the digits.)
BUBBLE_X = 306
h, w = alpha.shape
mint = np.zeros((h, w)); gray = np.zeros((h, w)); white = np.zeros((h, w))
for name, sl, other in (("gray", np.s_[:, :BUBBLE_X], gray), ("white", np.s_[:, BUBBLE_X:], white)):
    basis = np.array([INKS["mint"], INKS[name]], dtype=np.float64).T / 255.0  # 3x2
    P = premult[sl].reshape(-1, 3).T
    sol, *_ = np.linalg.lstsq(basis, P, rcond=None)
    sol = np.clip(sol, 0, None)
    tot = sol.sum(axis=0)
    a = alpha[sl].reshape(-1)
    sol = np.where(tot > 1e-6, sol / np.maximum(tot, 1e-6) * a, 0)
    shape = alpha[sl].shape
    mint[sl] = sol[0].reshape(shape)
    other[sl] = sol[1].reshape(shape)
layers = {"mint": np.clip(mint + white, 0, 1), "gray": gray, "white": white}


def trace(mask: np.ndarray) -> str:
    h, w = mask.shape
    big = Image.fromarray((mask * 255).astype(np.uint8)).resize((w * SCALE, h * SCALE), Image.LANCZOS)
    big = big.filter(ImageFilter.GaussianBlur(SCALE * 0.4))  # melt 1-px anti-alias steps
    bmp = potrace.Bitmap(np.asarray(big) <= 127)  # potracer: False = ink
    plist = bmp.trace(turdsize=30, turnpolicy=potrace.POTRACE_TURNPOLICY_MINORITY,
                      alphamax=0.9, opticurve=True, opttolerance=0.2)
    s = 1.0 / SCALE
    f = lambda p: f"{p.x * s:.2f},{p.y * s:.2f}"
    parts = []
    for curve in plist:
        parts.append(f"M{f(curve.start_point)}")
        for seg in curve.segments:
            if seg.is_corner:
                parts.append(f"L{f(seg.c)}L{f(seg.end_point)}")
            else:
                parts.append(f"C{f(seg.c1)} {f(seg.c2)} {f(seg.end_point)}")
        parts.append("Z")
    return "".join(parts)


paths = {k: trace(v) for k, v in layers.items()}
hexes = {k: "#%02X%02X%02X" % v for k, v in INKS.items()}
OUT_SVG.write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">\n'
    f"  <!-- Traced from chat360-ai-logo.png by studio/scripts/trace-logo.py. Do not hand-edit. -->\n"
    + "".join(f'  <path fill="{hexes[k]}" fill-rule="evenodd" d="{paths[k]}"/>\n' for k in ("mint", "gray", "white"))
    + "</svg>\n"
)
OUT_TS.write_text(
    "// Generated by scripts/trace-logo.py from public/brand/chat360-ai-logo.png. Do not hand-edit.\n"
    f"export const LOGO_VIEWBOX = {{ width: {w}, height: {h} }};\n"
    f"export const LOGO_INKS = {json.dumps(hexes)} as const;\n"
    f"export const LOGO_PATHS = {json.dumps(paths)} as const;\n"
)
print(OUT_SVG, OUT_SVG.stat().st_size, "bytes;", OUT_TS)
